# Generated by Django 2.0.7 on 2018-07-10 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diner_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_pos', models.IntegerField(default=0)),
                ('rating_neg', models.IntegerField(default=0)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diners.Diner')),
            ],
        ),
    ]
