# Generated by Django 2.0.7 on 2018-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0004_auto_20180907_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='diner',
            name='author',
        ),
    ]
