# Generated by Django 2.0.7 on 2018-09-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0006_auto_20180908_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='visted',
            field=models.TextField(default='No'),
        ),
    ]
